/**
 * Tests for src/applyPatch.ts — applying a real `git format-patch` series with
 * `git am --3way`, no agent. Uses the repo's real-git harness (bare remote +
 * seeded clone): every mbox fixture is generated by actually running
 * `git format-patch --stdout` in a scratch clone, never hand-approximated.
 */
import { describe, it, expect, afterEach } from "vitest";
import { mkdtempSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { execFileSync } from "node:child_process";

import { applyPatchSeries } from "../src/applyPatch.js";
import { parsePatchSeries, type PatchSeries } from "../src/patchTicket.js";
import type { RunResult } from "../src/types.js";
import { makeConfig } from "./helpers/config.js";
import { cloneHarness, run } from "./helpers/gitHarness.js";

function cfgFor(root: string) {
  return makeConfig({
    dataDir: root,
    queueRoot: join(root, "Junco"),
    worktreeRoot: join(root, "wts"),
    tools: [],
    criticEnabled: false,
    planLintEnabled: false,
    verifyEnabled: false,
    supervisorEnabled: false,
    healthEnabled: false,
    removeWorktreeOnSuccess: false,
  });
}

/** Wrap a raw mbox series in a junco-patch fence and run it through Task 1's
 * REAL parser — the fixture exercises the same parsing path prFlow does,
 * rather than hand-building a PatchSeries object. */
function toPatchSeries(raw: string): PatchSeries {
  const fenced = "````junco-patch\n" + raw + "````\n";
  const series = parsePatchSeries(fenced);
  if (series === null) throw new Error("test fixture: series failed to parse");
  return series;
}

/** Clone `workDir` into a throwaway scratch dir, apply `commits` (each writes
 * `file` with `content` and commits `message`), then `git format-patch -N
 * --stdout` the last N commits — a REAL mbox series, not an approximation.
 * The scratch clone is discarded; `workDir` itself is left untouched. */
function buildRealSeries(
  workDir: string,
  commits: Array<{ file: string; content: string; message: string }>,
): string {
  const scratch = mkdtempSync(join(tmpdir(), "junco-am-src-"));
  run(["git", "clone", "-q", workDir, scratch]);
  for (const c of commits) {
    writeFileSync(join(scratch, c.file), c.content, "utf8");
    run(["git", "-C", scratch, "add", "-A"]);
    run(["git", "-C", scratch, "commit", "-q", "-m", c.message]);
  }
  const raw = execFileSync(
    "git",
    ["-C", scratch, "format-patch", `-${commits.length}`, "--stdout"],
    { encoding: "utf8" },
  );
  rmSync(scratch, { recursive: true, force: true });
  return raw;
}

const LEVELS_10 = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"];

function levelsFile(entries: string[]): string {
  return "const LEVELS = [\n" + entries.map((e) => `  "${e}",`).join("\n") + "\n];\n";
}

describe("applyPatchSeries", () => {
  let roots: string[] = [];

  afterEach(() => {
    for (const r of roots) rmSync(r, { recursive: true, force: true });
    roots = [];
  });

  function setup(): { root: string; work: string } {
    const root = mkdtempSync(join(tmpdir(), "junco-applypatch-"));
    roots.push(root);
    const { work } = cloneHarness(root);
    return { root, work };
  }

  it("applies a one-patch series and creates one commit with the series' message", async () => {
    const { root, work } = setup();
    writeFileSync(join(work, "game.js"), levelsFile(["easy", "hard"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);
    const baseLog = run(["git", "-C", work, "log", "--oneline"]).trim().split("\n").length;

    const raw = buildRealSeries(work, [
      {
        file: "game.js",
        content: levelsFile(["easy", "medium", "hard"]),
        message: "feat: add a level",
      },
    ]);
    const series = toPatchSeries(raw);

    const cfg = cfgFor(root);
    const out = await applyPatchSeries(cfg, work, series);

    expect(out.ok).toBe(true);
    const log = run(["git", "-C", work, "log", "--oneline"]).trim().split("\n");
    expect(log.length).toBe(baseLog + 1);
    const subject = run(["git", "-C", work, "log", "-1", "--format=%s"]).trim();
    expect(subject).toBe("feat: add a level"); // no [PATCH] prefix
  });

  it("applies a two-patch series as two commits, in order", async () => {
    const { root, work } = setup();
    writeFileSync(join(work, "game.js"), levelsFile(["easy", "hard"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);
    const baseLog = run(["git", "-C", work, "log", "--oneline"]).trim().split("\n").length;

    const raw = buildRealSeries(work, [
      {
        file: "game.js",
        content: levelsFile(["easy", "medium", "hard"]),
        message: "feat: add medium",
      },
      {
        file: "game.js",
        content: levelsFile(["easy", "medium", "hard", "expert"]),
        message: "feat: add expert",
      },
    ]);
    const series = toPatchSeries(raw);
    expect(series.count).toBe(2);

    const cfg = cfgFor(root);
    const out = await applyPatchSeries(cfg, work, series);

    expect(out.ok).toBe(true);
    const log = run(["git", "-C", work, "log", "--oneline"]).trim().split("\n");
    expect(log.length).toBe(baseLog + 2);
    // Most-recent-first: expert landed after medium, in series order.
    const subjects = run(["git", "-C", work, "log", "-2", "--format=%s"]).trim().split("\n");
    expect(subjects).toEqual(["feat: add expert", "feat: add medium"]);
  });

  it("applies with 3-way when context drifted but the change is still mergeable", async () => {
    const { root, work } = setup();
    writeFileSync(join(work, "game.js"), levelsFile(LEVELS_10), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);

    // The series inserts "five-point-five" between five and six.
    const withInsert = [...LEVELS_10];
    withInsert.splice(withInsert.indexOf("five") + 1, 0, "five-point-five");
    const raw = buildRealSeries(work, [
      { file: "game.js", content: levelsFile(withInsert), message: "feat: add five-point-five" },
    ]);
    const series = toPatchSeries(raw);

    // Commit an UNRELATED edit elsewhere in the same file — two lines away
    // from the insertion point (within the patch's context window, so a
    // plain (non-3way) apply's context match fails), before applying.
    const drifted = LEVELS_10.map((e) => (e === "three" ? "three (annotated)" : e));
    writeFileSync(join(work, "game.js"), levelsFile(drifted), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "chore: annotate three"]);

    const cfg = cfgFor(root);
    const out = await applyPatchSeries(cfg, work, series);

    expect(out.ok).toBe(true);
    const contents = execFileSync("cat", [join(work, "game.js")], { encoding: "utf8" });
    expect(contents).toContain("five-point-five"); // the series' change landed
    expect(contents).toContain("three (annotated)"); // the drift survived, merged
  });

  it("fails cleanly on a real conflict, aborts the am, and leaves the worktree clean", async () => {
    const { root, work } = setup();
    writeFileSync(join(work, "game.js"), levelsFile(["one", "two", "three"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);

    // The series renames "two" one way...
    const raw = buildRealSeries(work, [
      {
        file: "game.js",
        content: levelsFile(["one", "TWO-CHANGED", "three"]),
        message: "feat: rename two",
      },
    ]);
    const conflicting = toPatchSeries(raw);

    // ...while the worktree independently renamed the SAME line differently —
    // an unresolvable conflict even with --3way.
    writeFileSync(join(work, "game.js"), levelsFile(["one", "dos", "three"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "chore: rename two differently"]);

    const cfg = cfgFor(root);
    const out = await applyPatchSeries(cfg, work, conflicting);

    expect(out.ok).toBe(false);
    expect((out as { reason: string }).reason).toMatch(/conflict|failed/i);
    expect(run(["git", "-C", work, "status", "--porcelain"]).trim()).toBe("");
    expect(existsSync(join(work, ".git", "rebase-apply"))).toBe(false);
  });

  it("reports zero usage and an apply stopReason on success", async () => {
    const { root, work } = setup();
    writeFileSync(join(work, "game.js"), levelsFile(["easy", "hard"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);

    const raw = buildRealSeries(work, [
      {
        file: "game.js",
        content: levelsFile(["easy", "medium", "hard"]),
        message: "feat: add a level",
      },
    ]);
    const series = toPatchSeries(raw);

    const cfg = cfgFor(root);
    const out = await applyPatchSeries(cfg, work, series);

    expect(out.ok).toBe(true);
    const result = (out as { result: RunResult }).result;
    expect(result.usage.total).toBe(0);
    expect(result.stopReason).toBe("apply");
    expect(result.toolCalls).toEqual([]);
  });
});
