/**
 * Tests for src/applyPatch.ts — applying a real `git format-patch` series with
 * `git am --3way`, no agent. Uses the repo's real-git harness (bare remote +
 * seeded clone): every mbox fixture is generated by actually running
 * `git format-patch --stdout` in a scratch clone, never hand-approximated.
 */
import { describe, it, expect, afterEach } from "vitest";
import { mkdtempSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { execFileSync } from "node:child_process";

import { applyPatchSeries, buildApplyFallbackPrompt } from "../src/applyPatch.js";
import { parsePatchSeries, type PatchSeries } from "../src/patchTicket.js";
import type { Config, RunResult } from "../src/types.js";
import { parseTicket } from "../src/ticket.js";
import { makeConfig } from "./helpers/config.js";
import { cloneHarness, run } from "./helpers/gitHarness.js";
import { dataTreePaths } from "../src/dataTree.js";
import { transcriptPathFor } from "../src/slug.js";
import { parseTranscriptLine, type JuncoRecord } from "../src/agent/transcriptSchema.js";

function cfgFor(root: string, overrides: Partial<Config> = {}) {
  return makeConfig(
    {
      dataDir: root,
      queueRoot: join(root, "Junco"),
      worktreeRoot: join(root, "wts"),
      tools: [],
      criticEnabled: false,
      planLintEnabled: false,
      verifyEnabled: false,
      supervisorEnabled: false,
      healthEnabled: false,
      removeWorktreeOnSuccess: false,
    },
    overrides,
  );
}

/** Wrap a raw mbox series in a junco-patch fence and run it through Task 1's
 * REAL parser — the fixture exercises the same parsing path prFlow does,
 * rather than hand-building a PatchSeries object. */
function toPatchSeries(raw: string): PatchSeries {
  const fenced = "````junco-patch\n" + raw + "````\n";
  const series = parsePatchSeries(fenced);
  if (series === null) throw new Error("test fixture: series failed to parse");
  return series;
}

/** Clone `workDir` into a throwaway scratch dir, apply `commits` (each writes
 * `file` with `content` and commits `message`), then `git format-patch -N
 * --stdout` the last N commits — a REAL mbox series, not an approximation.
 * The scratch clone is discarded; `workDir` itself is left untouched. */
function buildRealSeries(
  workDir: string,
  commits: Array<{ file: string; content: string; message: string }>,
): string {
  const scratch = mkdtempSync(join(tmpdir(), "junco-am-src-"));
  run(["git", "clone", "-q", workDir, scratch]);
  for (const c of commits) {
    writeFileSync(join(scratch, c.file), c.content, "utf8");
    run(["git", "-C", scratch, "add", "-A"]);
    run(["git", "-C", scratch, "commit", "-q", "-m", c.message]);
  }
  const raw = execFileSync(
    "git",
    ["-C", scratch, "format-patch", `-${commits.length}`, "--stdout"],
    { encoding: "utf8" },
  );
  rmSync(scratch, { recursive: true, force: true });
  return raw;
}

const LEVELS_10 = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"];

function levelsFile(entries: string[]): string {
  return "const LEVELS = [\n" + entries.map((e) => `  "${e}",`).join("\n") + "\n];\n";
}

describe("applyPatchSeries", () => {
  let roots: string[] = [];

  afterEach(() => {
    for (const r of roots) rmSync(r, { recursive: true, force: true });
    roots = [];
  });

  function setup(): { root: string; work: string } {
    const root = mkdtempSync(join(tmpdir(), "junco-applypatch-"));
    roots.push(root);
    const { work } = cloneHarness(root);
    return { root, work };
  }

  it("applies a one-patch series and creates one commit with the series' message", async () => {
    const { root, work } = setup();
    writeFileSync(join(work, "game.js"), levelsFile(["easy", "hard"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);
    const baseLog = run(["git", "-C", work, "log", "--oneline"]).trim().split("\n").length;

    const raw = buildRealSeries(work, [
      {
        file: "game.js",
        content: levelsFile(["easy", "medium", "hard"]),
        message: "feat: add a level",
      },
    ]);
    const series = toPatchSeries(raw);

    const cfg = cfgFor(root);
    const out = await applyPatchSeries(cfg, work, "t1", series);

    expect(out.ok).toBe(true);
    const log = run(["git", "-C", work, "log", "--oneline"]).trim().split("\n");
    expect(log.length).toBe(baseLog + 1);
    const subject = run(["git", "-C", work, "log", "-1", "--format=%s"]).trim();
    expect(subject).toBe("feat: add a level"); // no [PATCH] prefix
  });

  it("applies a two-patch series as two commits, in order", async () => {
    const { root, work } = setup();
    writeFileSync(join(work, "game.js"), levelsFile(["easy", "hard"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);
    const baseLog = run(["git", "-C", work, "log", "--oneline"]).trim().split("\n").length;

    const raw = buildRealSeries(work, [
      {
        file: "game.js",
        content: levelsFile(["easy", "medium", "hard"]),
        message: "feat: add medium",
      },
      {
        file: "game.js",
        content: levelsFile(["easy", "medium", "hard", "expert"]),
        message: "feat: add expert",
      },
    ]);
    const series = toPatchSeries(raw);
    expect(series.count).toBe(2);

    const cfg = cfgFor(root);
    const out = await applyPatchSeries(cfg, work, "t1", series);

    expect(out.ok).toBe(true);
    const log = run(["git", "-C", work, "log", "--oneline"]).trim().split("\n");
    expect(log.length).toBe(baseLog + 2);
    // Most-recent-first: expert landed after medium, in series order.
    const subjects = run(["git", "-C", work, "log", "-2", "--format=%s"]).trim().split("\n");
    expect(subjects).toEqual(["feat: add expert", "feat: add medium"]);
  });

  it("applies with 3-way when context drifted but the change is still mergeable", async () => {
    const { root, work } = setup();
    writeFileSync(join(work, "game.js"), levelsFile(LEVELS_10), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);

    // The series inserts "five-point-five" between five and six.
    const withInsert = [...LEVELS_10];
    withInsert.splice(withInsert.indexOf("five") + 1, 0, "five-point-five");
    const raw = buildRealSeries(work, [
      { file: "game.js", content: levelsFile(withInsert), message: "feat: add five-point-five" },
    ]);
    const series = toPatchSeries(raw);

    // Commit an UNRELATED edit elsewhere in the same file — two lines away
    // from the insertion point (within the patch's context window, so a
    // plain (non-3way) apply's context match fails), before applying.
    const drifted = LEVELS_10.map((e) => (e === "three" ? "three (annotated)" : e));
    writeFileSync(join(work, "game.js"), levelsFile(drifted), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "chore: annotate three"]);

    const cfg = cfgFor(root);
    const out = await applyPatchSeries(cfg, work, "t1", series);

    expect(out.ok).toBe(true);
    const contents = execFileSync("cat", [join(work, "game.js")], { encoding: "utf8" });
    expect(contents).toContain("five-point-five"); // the series' change landed
    expect(contents).toContain("three (annotated)"); // the drift survived, merged
  });

  it("fails cleanly on a real conflict, aborts the am, and leaves the worktree clean", async () => {
    const { root, work } = setup();
    writeFileSync(join(work, "game.js"), levelsFile(["one", "two", "three"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);

    // The series renames "two" one way...
    const raw = buildRealSeries(work, [
      {
        file: "game.js",
        content: levelsFile(["one", "TWO-CHANGED", "three"]),
        message: "feat: rename two",
      },
    ]);
    const conflicting = toPatchSeries(raw);

    // ...while the worktree independently renamed the SAME line differently —
    // an unresolvable conflict even with --3way.
    writeFileSync(join(work, "game.js"), levelsFile(["one", "dos", "three"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "chore: rename two differently"]);

    const cfg = cfgFor(root);
    const out = await applyPatchSeries(cfg, work, "t1", conflicting);

    expect(out.ok).toBe(false);
    expect((out as { reason: string }).reason).toMatch(/conflict|failed/i);
    expect(run(["git", "-C", work, "status", "--porcelain"]).trim()).toBe("");
    expect(existsSync(join(work, ".git", "rebase-apply"))).toBe(false);
  });

  it("reports zero usage and an apply stopReason on success", async () => {
    const { root, work } = setup();
    writeFileSync(join(work, "game.js"), levelsFile(["easy", "hard"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);

    const raw = buildRealSeries(work, [
      {
        file: "game.js",
        content: levelsFile(["easy", "medium", "hard"]),
        message: "feat: add a level",
      },
    ]);
    const series = toPatchSeries(raw);

    const cfg = cfgFor(root);
    const out = await applyPatchSeries(cfg, work, "t1", series);

    expect(out.ok).toBe(true);
    const result = (out as { result: RunResult }).result;
    expect(result.usage.total).toBe(0);
    expect(result.stopReason).toBe("apply");
    expect(result.toolCalls).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// applyPatchSeries — transcript frames for agent-less runs (Stage 4a):
// closes Stage 1's documented "apply tickets produce no transcript" gap.
// ---------------------------------------------------------------------------

describe("applyPatchSeries — transcript frames (Stage 4a)", () => {
  let roots: string[] = [];

  afterEach(() => {
    for (const r of roots) rmSync(r, { recursive: true, force: true });
    roots = [];
  });

  function setup(): { root: string; work: string } {
    const root = mkdtempSync(join(tmpdir(), "junco-applypatch-tx-"));
    roots.push(root);
    const { work } = cloneHarness(root);
    return { root, work };
  }

  /** One clean, applicable one-commit series touching game.js. */
  function cleanSeries(work: string): PatchSeries {
    writeFileSync(join(work, "game.js"), levelsFile(["easy", "hard"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);
    const raw = buildRealSeries(work, [
      {
        file: "game.js",
        content: levelsFile(["easy", "medium", "hard"]),
        message: "feat: add a level",
      },
    ]);
    return toPatchSeries(raw);
  }

  /** A series guaranteed to conflict with the current tip of `work` (mirrors
   * the "fails cleanly on a real conflict" fixture above). */
  function conflictingSeries(work: string): PatchSeries {
    writeFileSync(join(work, "game.js"), levelsFile(["one", "two", "three"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add game.js"]);
    const raw = buildRealSeries(work, [
      {
        file: "game.js",
        content: levelsFile(["one", "TWO-CHANGED", "three"]),
        message: "feat: rename two",
      },
    ]);
    const conflicting = toPatchSeries(raw);
    writeFileSync(join(work, "game.js"), levelsFile(["one", "dos", "three"]), "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "chore: rename two differently"]);
    return conflicting;
  }

  function parseFrames(lines: string[]): JuncoRecord[] {
    return lines.map((l) => {
      const parsed = parseTranscriptLine(l);
      if (parsed.kind !== "junco") throw new Error(`unexpected non-junco line: ${l}`);
      return parsed.record;
    });
  }

  /** In-memory transcript sink (mirrors tests/runEnvelope.test.ts's memorySink):
   * avoids the real fs sink's async open/flush, which races a synchronous
   * read run immediately after applyPatchSeries resolves. fileExists reflects
   * whether anything has been written yet, so a second call against the same
   * sink observes "the file already exists" exactly like the real fs would. */
  function memorySink(): {
    lines: string[];
    transcriptSink: () => { write: (l: string) => void; end: () => void };
    fileExists: () => boolean;
  } {
    const lines: string[] = [];
    return {
      lines,
      transcriptSink: () => ({
        write: (l: string) => void lines.push(l),
        end: () => {},
      }),
      fileExists: () => lines.length > 0,
    };
  }

  it("a successful apply writes junco_meta + junco_run_start(flow apply) + junco_run_end(stopReason apply), no turn/tool frames", async () => {
    const { root, work } = setup();
    const series = cleanSeries(work);
    const cfg = cfgFor(root, { transcriptsEnabled: true });
    const mem = memorySink();

    const out = await applyPatchSeries(cfg, work, "apply-tx-ok", series, {
      transcriptSink: mem.transcriptSink,
      fileExists: mem.fileExists,
    });
    expect(out.ok).toBe(true);

    const frames = parseFrames(mem.lines);
    expect(frames.map((f) => f.type)).toEqual(["junco_meta", "junco_run_start", "junco_run_end"]);

    const meta = frames[0] as { type: "junco_meta"; ticketId: string };
    expect(meta.ticketId).toBe("apply-tx-ok");

    const start = frames[1] as { type: "junco_run_start"; flow: string; body: string };
    expect(start.flow).toBe("apply");
    expect(start.body).toContain("1 patch");
    expect(start.body).toContain("game.js");

    const end = frames[2] as {
      type: "junco_run_end";
      stopReason: string | null;
      usage: { total: number; costUsd: number };
      errorMessage: string | null;
      durationMs: number;
    };
    expect(end.stopReason).toBe("apply");
    expect(end.usage).toEqual({ input: 0, output: 0, cacheRead: 0, total: 0, costUsd: 0 });
    expect(end.errorMessage).toBeNull();
    expect(end.durationMs).toBeGreaterThanOrEqual(0);
  });

  it("cfg.transcriptsEnabled: false writes nothing", async () => {
    const { root, work } = setup();
    const series = cleanSeries(work);
    const cfg = cfgFor(root); // transcriptsEnabled defaults false (tests/helpers/config.ts)

    const out = await applyPatchSeries(cfg, work, "apply-tx-off", series);
    expect(out.ok).toBe(true);

    const path = transcriptPathFor(dataTreePaths(cfg).transcripts, "apply-tx-off");
    expect(existsSync(path)).toBe(false);
  });

  it("a failed apply writes no transcript frames (nothing ran to completion)", async () => {
    const { root, work } = setup();
    const conflicting = conflictingSeries(work);
    const cfg = cfgFor(root, { transcriptsEnabled: true });

    const out = await applyPatchSeries(cfg, work, "apply-tx-fail", conflicting);
    expect(out.ok).toBe(false);

    const path = transcriptPathFor(dataTreePaths(cfg).transcripts, "apply-tx-fail");
    expect(existsSync(path)).toBe(false);
  });

  it("two apply runs against the same ticket id append to one file without a duplicate junco_meta", async () => {
    const { root, work } = setup();
    const cfg = cfgFor(root, { transcriptsEnabled: true });
    const mem = memorySink();
    const series1 = cleanSeries(work);
    const out1 = await applyPatchSeries(cfg, work, "apply-tx-dup", series1, {
      transcriptSink: mem.transcriptSink,
      fileExists: mem.fileExists,
    });
    expect(out1.ok).toBe(true);

    writeFileSync(join(work, "other.js"), "one\n", "utf8");
    run(["git", "-C", work, "add", "-A"]);
    run(["git", "-C", work, "commit", "-q", "-m", "feat: add other.js"]);
    const raw2 = buildRealSeries(work, [
      { file: "other.js", content: "one\ntwo\n", message: "feat: extend other" },
    ]);
    const series2 = toPatchSeries(raw2);
    const out2 = await applyPatchSeries(cfg, work, "apply-tx-dup", series2, {
      transcriptSink: mem.transcriptSink,
      fileExists: mem.fileExists,
    });
    expect(out2.ok).toBe(true);

    const frames = parseFrames(mem.lines);
    expect(frames.filter((f) => f.type === "junco_meta")).toHaveLength(1);
    expect(frames.map((f) => f.type)).toEqual([
      "junco_meta",
      "junco_run_start",
      "junco_run_end",
      "junco_run_start",
      "junco_run_end",
    ]);
  });
});

// ---------------------------------------------------------------------------
// buildApplyFallbackPrompt — Stage 2a escalation ladder.
// ---------------------------------------------------------------------------

describe("buildApplyFallbackPrompt", () => {
  const series: PatchSeries = {
    raw:
      "From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001\n" +
      "Subject: [PATCH] feat: add levels 15-19\n\n" +
      "diff --git a/game.js b/game.js\n" +
      "index abc1234..def5678 100644\n" +
      "--- a/game.js\n" +
      "+++ b/game.js\n" +
      "@@ -1,3 +1,4 @@\n" +
      '+  "fifteen",\n',
    count: 1,
    files: ["game.js"],
  };
  const task = parseTicket(
    "/q/t.md",
    "---\nid: t\nrepo: /r\n---\n# Add levels 15-19\n\nExtend the LEVELS array in game.js.\n",
    30,
  );

  it("contains the ticket's prose, the series verbatim, and the failure reason", () => {
    const prompt = buildApplyFallbackPrompt(task, series, {
      kind: "apply",
      detail: "git am --3way failed (exit 128): conflict in game.js",
    });
    expect(prompt).toContain("Extend the LEVELS array in game.js.");
    expect(prompt).toContain(series.raw); // the series verbatim — the agent must read the diff
    expect(prompt).toContain("git am --3way failed (exit 128): conflict in game.js");
  });

  it("instructs implementing the intended change against current reality, not replaying bytes", () => {
    const prompt = buildApplyFallbackPrompt(task, series, {
      kind: "apply",
      detail: "conflict",
    });
    expect(prompt).toMatch(/treat it as the\s*\n?\s*specification/i);
    expect(prompt).toMatch(/implement the same\s*\n?\s*intent against what is actually there/i);
  });

  it("never tells the agent to run git am or git apply — the series already failed", () => {
    const prompt = buildApplyFallbackPrompt(task, series, { kind: "apply", detail: "conflict" });
    expect(prompt).toMatch(/do not run `git am` or `git apply`/i);
    // A prohibition, not a step: no bare imperative line telling it to run either.
    expect(prompt).not.toMatch(/^\s*git am\b/m);
    expect(prompt).not.toMatch(/^\s*git apply\b/m);
  });

  it("a verification-kind failure names the Verification block instead of the apply step", () => {
    const prompt = buildApplyFallbackPrompt(task, series, {
      kind: "verification",
      detail: "grep -q 'line one' feature.txt failed (exit 1)",
    });
    expect(prompt).toMatch(/applied cleanly.*Verification.*failed/i);
    expect(prompt).toContain("grep -q 'line one' feature.txt failed (exit 1)");
  });
});
