/**
 * Interactive setup wizard for `junco init` — prompts for the essentials,
 * writes a `config.toml`, and creates the queue directories. Runs fine over
 * `npx` (it's a normal TTY invocation). The pure pieces (`renderConfigToml`,
 * `collectAnswers` with an injected `ask`) are unit-testable without real stdin.
 */

import * as readline from "node:readline/promises";
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import type { Config } from "./types.js";
import { loadConfig, queuePaths } from "./config.js";

export interface WizardAnswers {
  vaultRoot: string;
  mode: "inline" | "models_json";
  modelId: string;
  baseUrl?: string; // inline mode
  apiKey?: string; // inline mode
  modelsJson?: string; // models_json mode
}

/** Prompt abstraction so the wizard is testable with scripted answers. */
export type AskFn = (question: string, opts?: { default?: string }) => Promise<string>;

// Quote + escape a value for a TOML basic string.
function tomlStr(s: string): string {
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

/**
 * Render a minimal, commented config.toml from the wizard answers. Pure — its
 * output must round-trip through `loadConfig`. Only the essentials are written;
 * every other knob falls back to its documented default.
 */
export function renderConfigToml(a: WizardAnswers): string {
  const lines: string[] = [
    "# Junco configuration — generated by `junco init`.",
    "# Full reference + all options: https://github.com/ironforgesoftware/junco#configuration",
    "",
    `vault_root = ${tomlStr(a.vaultRoot)}   # queue lives at <vault_root>/Junco/{inbox,processing,done,failed}`,
    "",
    "[model]",
    `id = ${tomlStr(a.modelId)}   # provider-prefixed model id`,
  ];
  if (a.mode === "models_json") {
    lines.push(
      `models_json = ${tomlStr(a.modelsJson ?? "~/.pi/agent/models.json")}   # provider+model loaded from this Pi-style models.json`,
    );
  } else {
    lines.push(
      `base_url = ${tomlStr(a.baseUrl ?? "http://127.0.0.1:1234/v1")}   # any OpenAI-compatible /v1 endpoint`,
      `api_key = ${tomlStr(a.apiKey ?? "")}`,
    );
  }
  return lines.join("\n") + "\n";
}

/** Defaults used by `--yes` (non-interactive scaffold). */
export function defaultAnswers(): WizardAnswers {
  return {
    vaultRoot: "~/junco-vault",
    mode: "inline",
    modelId: "omlx/my-model",
    baseUrl: "http://127.0.0.1:1234/v1",
    apiKey: "1234",
  };
}

/** The interactive prompt script. Short — only the essentials. */
export async function collectAnswers(ask: AskFn): Promise<WizardAnswers> {
  const vaultRoot = await ask("Where should the work queue live (vault directory)?", {
    default: "~/junco-vault",
  });
  const modeRaw = (
    await ask("Configure the model inline, or point at a Pi models.json? [inline/models-json]", {
      default: "inline",
    })
  ).toLowerCase();
  const mode: WizardAnswers["mode"] = modeRaw.startsWith("m") ? "models_json" : "inline";
  const modelId = await ask("Model id (provider-prefixed, e.g. omlx/Qwen3.6-27B-oQ8-mtp)?", {
    default: "omlx/my-model",
  });

  if (mode === "models_json") {
    const modelsJson = await ask("Path to your Pi models.json?", {
      default: "~/.pi/agent/models.json",
    });
    return { vaultRoot, mode, modelId, modelsJson };
  }
  const baseUrl = await ask("Inference endpoint base URL (OpenAI-compatible)?", {
    default: "http://127.0.0.1:1234/v1",
  });
  const apiKey = await ask("API key for the endpoint?", { default: "1234" });
  return { vaultRoot, mode, modelId, baseUrl, apiKey };
}

export interface WizardDeps {
  /** Injected prompt fn (tests). When omitted, a readline-backed prompt is used. */
  ask?: AskFn;
  /** Skip prompts and scaffold from defaults (--yes). */
  yes?: boolean;
  writeFileFn?: (path: string, content: string) => void;
  loadConfigFn?: (path: string) => Config;
  mkdirFn?: (path: string) => void;
  printFn?: (s: string) => void;
}

/**
 * Run the setup wizard: collect answers → write config.toml → load it → create
 * the queue dirs → print next steps. Returns an exit code.
 */
export async function runInitWizard(configPath: string, deps: WizardDeps = {}): Promise<number> {
  const writeFileFn = deps.writeFileFn ?? ((p, c) => writeFileSync(p, c, "utf8"));
  const loadConfigFn = deps.loadConfigFn ?? loadConfig;
  const mkdirFn = deps.mkdirFn ?? ((p) => mkdirSync(p, { recursive: true }));
  const printFn = deps.printFn ?? ((s) => process.stdout.write(s));

  // Build the prompt fn: injected (tests) or a single readline interface.
  let ask = deps.ask;
  let rl: readline.Interface | undefined;
  if (!ask && !deps.yes) {
    rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    ask = async (q, o) => {
      const suffix = o?.default ? ` [${o.default}]` : "";
      const a = (await rl!.question(`${q}${suffix} `)).trim();
      return a || (o?.default ?? "");
    };
  }

  try {
    const answers = deps.yes ? defaultAnswers() : await collectAnswers(ask!);
    const toml = renderConfigToml(answers);
    const resolved = resolve(configPath);
    mkdirFn(dirname(resolved)); // ensure the config's parent dir exists
    writeFileFn(resolved, toml);

    // Load the freshly-written config and create the queue dirs from it.
    const cfg = loadConfigFn(resolved);
    const paths = queuePaths(cfg);
    for (const d of [paths.inbox, paths.processing, paths.done, paths.failed, cfg.worktreeRoot]) {
      mkdirFn(d);
    }

    const queueRoot = dirname(paths.inbox);
    printFn(
      `\n✓ Wrote config:  ${resolved}\n` +
        `✓ Created queue: ${queueRoot}/{inbox,processing,done,failed}\n\n` +
        `Next steps:\n` +
        `  • Tweak the model/endpoint in ${resolved} if needed.\n` +
        `  • Start the worker:  junco start --config ${resolved}\n` +
        `  • Submit a ticket:   junco submit <ticket>.md --config ${resolved}\n`,
    );
    return 0;
  } finally {
    rl?.close();
  }
}
