/**
 * Interactive setup wizard for `junco init` — a colorized clack TUI that prompts
 * for the essentials, discovers available models from the endpoint (or a Pi
 * models.json), writes a `config.toml`, and creates the queue directories.
 *
 * Testability: the prompt surface is the injectable `Prompter` seam (clack in
 * production, a scripted prompter in tests), and `renderConfigToml` is pure — so
 * the wizard's logic is exercised without a real TTY.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import type { Config } from "./types.js";
import { loadConfig, queuePaths, expandHome, resolveConfigPath } from "./config.js";
import { type Prompter, WizardCancelled, clackPrompter } from "./wizard/prompter.js";
import { fetchModels, parseModelsJson, inferProvider } from "./wizard/models.js";

/** `select` sentinel for the "enter manually" escape hatch (not a real model id). */
const MANUAL = " manual";

export interface WizardAnswers {
  vaultRoot: string;
  mode: "inline" | "models_json";
  modelId: string;
  baseUrl?: string; // inline mode
  apiKey?: string; // inline mode
  modelsJson?: string; // models_json mode
}

// Quote + escape a value for a TOML basic string.
function tomlStr(s: string): string {
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

/**
 * Render a minimal, commented config.toml from the wizard answers. Pure — its
 * output must round-trip through `loadConfig`. Writes `junco_subdir = ""` so the
 * queue lives directly under `vault_root` (no redundant `Junco/` nesting); the
 * schema default stays `"Junco"` for existing shared-vault configs.
 */
export function renderConfigToml(a: WizardAnswers): string {
  const lines: string[] = [
    "# Junco configuration — generated by `junco init`.",
    "# Full reference + all options: https://github.com/ironforgesoftware/junco/blob/main/docs/configuration.md",
    "",
    `vault_root = ${tomlStr(a.vaultRoot)}   # queue lives at <vault_root>/{inbox,processing,done,failed}`,
    `junco_subdir = ""   # tickets live directly under vault_root`,
    "",
    "[model]",
    `id = ${tomlStr(a.modelId)}   # provider-prefixed model id`,
  ];
  if (a.mode === "models_json") {
    lines.push(
      `models_json = ${tomlStr(a.modelsJson ?? "~/.pi/agent/models.json")}   # provider+model loaded from this models.json`,
    );
  } else {
    lines.push(
      `base_url = ${tomlStr(a.baseUrl ?? "http://127.0.0.1:1234/v1")}   # any OpenAI-compatible /v1 endpoint`,
      `api_key = ${tomlStr(a.apiKey ?? "")}`,
    );
  }
  lines.push(
    "",
    "# --- GitHub-integrated mode (optional) --------------------------------------",
    "# Bridge trigger-labeled GitHub issues into the inbox and report results back",
    "# to the issue (lifecycle labels + one comment). Uses your existing `gh` auth.",
    "# [github]",
    "# enabled = true",
    '# trigger_label = "junco"   # the label is the approval; review issues before labeling',
    "# poll_interval_seconds = 60",
    "# require_approval = true  # plans wait for a junco:approved label from a writer",
    "#",
    "# [[github.repos]]",
    '# nwo  = "owner/repo"',
    '# path = "~/code/repo"      # local clone; its origin must point at nwo',
  );
  return lines.join("\n") + "\n";
}

/** Defaults used by `--yes` (non-interactive scaffold). */
export function defaultAnswers(): WizardAnswers {
  return {
    vaultRoot: "~/Junco",
    mode: "inline",
    modelId: "local/my-model",
    baseUrl: "http://127.0.0.1:1234/v1",
    apiKey: "1234",
  };
}

export interface CollectDeps {
  fetchModelsFn?: typeof fetchModels;
  parseModelsJsonFn?: typeof parseModelsJson;
}

function hostOf(url: string): string {
  try {
    return new URL(url).host;
  } catch {
    return url;
  }
}

/** Show discovered ids as a select (+ a manual escape hatch); empty list → manual prompt. */
async function pickModel(p: Prompter, ids: string[]): Promise<string> {
  if (ids.length > 0) {
    const choice = await p.select({
      message: "Select a model",
      options: [
        ...ids.map((id) => ({ value: id, label: id })),
        { value: MANUAL, label: "✏️  Enter manually…" },
      ],
    });
    if (choice !== MANUAL) return choice;
  }
  return p.text({ message: "Model id?", default: "my-model" });
}

/** The interactive prompt script over the Prompter seam. */
export async function collectAnswers(p: Prompter, deps: CollectDeps = {}): Promise<WizardAnswers> {
  const fetchModelsFn = deps.fetchModelsFn ?? fetchModels;
  const parseModelsJsonFn = deps.parseModelsJsonFn ?? parseModelsJson;

  p.intro("junco init");
  const vaultRoot = await p.text({
    message: "Where should Junco keep its tickets?",
    default: "~/Junco",
  });
  const mode = (await p.select({
    message: "How is the model configured?",
    options: [
      { value: "inline", label: "Inline — an OpenAI-compatible endpoint" },
      { value: "models_json", label: "From a Pi models.json file" },
    ],
  })) as WizardAnswers["mode"];

  if (mode === "models_json") {
    const modelsJson = await p.text({
      message: "Path to your Pi models.json?",
      default: "~/.pi/agent/models.json",
    });
    const ids = parseModelsJsonFn(expandHome(modelsJson));
    const modelId = await pickModel(p, ids);
    return { vaultRoot, mode, modelId, modelsJson };
  }

  const baseUrl = await p.text({
    message: "Inference endpoint base URL (OpenAI-compatible)?",
    default: "http://127.0.0.1:1234/v1",
  });
  const apiKey = await p.text({ message: "API key for the endpoint?", default: "1234" });
  const ids = await p.spinner(
    `Fetching models from ${hostOf(baseUrl)}…`,
    () => fetchModelsFn(baseUrl, apiKey),
    (r) => `${r.length} model${r.length === 1 ? "" : "s"} found`,
  );
  const picked = await pickModel(p, ids);
  // Discovered/typed bare ids get the inferred provider prefix; ids that already
  // contain "/" (manual full ids, OpenRouter-style vendor/model) are kept as-is.
  const modelId = picked.includes("/") ? picked : `${inferProvider(baseUrl)}/${picked}`;
  return { vaultRoot, mode, modelId, baseUrl, apiKey };
}

export interface WizardDeps {
  /** Injected prompt surface (tests). When omitted, a clack-backed prompter is used. */
  prompter?: Prompter;
  /** Skip prompts and scaffold from defaults (--yes). */
  yes?: boolean;
  fetchModelsFn?: typeof fetchModels;
  parseModelsJsonFn?: typeof parseModelsJson;
  writeFileFn?: (path: string, content: string) => void;
  loadConfigFn?: (path: string) => Config;
  mkdirFn?: (path: string) => void;
  printFn?: (s: string) => void;
}

/**
 * Run the setup wizard: collect answers → write config.toml → load it → create
 * the queue dirs → print next steps. Returns an exit code (0 ok, 130 cancelled).
 */
export async function runInitWizard(configPath: string, deps: WizardDeps = {}): Promise<number> {
  const writeFileFn = deps.writeFileFn ?? ((p, c) => writeFileSync(p, c, "utf8"));
  const loadConfigFn = deps.loadConfigFn ?? loadConfig;
  const mkdirFn = deps.mkdirFn ?? ((p) => mkdirSync(p, { recursive: true }));
  const printFn = deps.printFn ?? ((s) => process.stdout.write(s));

  try {
    let answers: WizardAnswers;
    if (deps.yes) {
      answers = defaultAnswers();
    } else {
      const prompter = deps.prompter ?? clackPrompter();
      answers = await collectAnswers(prompter, {
        fetchModelsFn: deps.fetchModelsFn,
        parseModelsJsonFn: deps.parseModelsJsonFn,
      });
    }

    const toml = renderConfigToml(answers);
    const resolved = resolve(configPath);
    mkdirFn(dirname(resolved)); // ensure the config's parent dir exists
    writeFileFn(resolved, toml);

    // Load the freshly-written config and create the queue dirs from it.
    const cfg = loadConfigFn(resolved);
    const paths = queuePaths(cfg);
    for (const d of [paths.inbox, paths.processing, paths.done, paths.failed, cfg.worktreeRoot]) {
      mkdirFn(d);
    }

    const queueRoot = dirname(paths.inbox);
    // No --config noise when the config landed on the default resolution path —
    // a bare `junco start` will find it from any directory.
    const flag = resolved === resolveConfigPath(undefined) ? "" : ` --config ${resolved}`;
    printFn(
      `\n✓ Wrote config:  ${resolved}\n` +
        `✓ Created queue: ${queueRoot}/{inbox,processing,done,failed}\n\n` +
        `Next steps:\n` +
        `  • Tweak the model/endpoint in ${resolved} if needed.\n` +
        `  • Start the worker:  junco start${flag}\n` +
        `  • Submit a ticket:   junco submit <ticket>.md${flag}\n`,
    );
    return 0;
  } catch (e) {
    if (e instanceof WizardCancelled) return 130; // clack.cancel() already printed
    throw e;
  }
}
